name: Download, Install DJGPP Toolchain, and Compile

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  setup-and-compile-djgpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up directories
        run: |
          mkdir -p ~/djgpp

      - name: Download DJGPP toolchain
        run: |
          curl -L https://github.com/andrewwutw/build-djgpp/releases/download/v3.3/djgpp-linux64-gcc1210.tar.bz2 -o ~/djgpp-linux64-gcc1210.tar.bz2

      - name: Extract DJGPP toolchain
        run: |
          tar -xjf ~/djgpp-linux64-gcc1210.tar.bz2 -C ~/
      
      - name: Install libfl-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libfl-dev

      - name: Compile DJGPP library
        run: ./xmake.sh lib

      - name: Upload liballeg.a to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ~/lib/djgpp/liballeg.a
          asset_name: liballeg.a
          asset_content_type: application/octet-stream
          asset_label: liballeg.a
          token: ${{ secrets.GITHUB_TOKEN }}
