name: Download, Install DJGPP Toolchain, and Compile

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  setup-and-compile-djgpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up directories
        run: |
          mkdir -p ~/djgpp

      - name: Download DJGPP toolchain
        run: |
          curl -L https://github.com/andrewwutw/build-djgpp/releases/download/v3.3/djgpp-linux64-gcc1210.tar.bz2 -o ~/djgpp/djgpp-linux64-gcc1210.tar.bz2

      - name: Extract DJGPP toolchain
        run: |
          tar -xjf ~/djgpp/djgpp-linux64-gcc1210.tar.bz2 -C ~/djgpp/

      - name: Compile DJGPP library
        run: ./xmake.sh lib
