name: Download, Install DJGPP Toolchain, and Compile

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  setup-and-compile-djgpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up directories
        run: |
          mkdir -p ~/djgpp

      - name: Download DJGPP toolchain
        run: |
          curl -L https://github.com/andrewwutw/build-djgpp/releases/download/v3.3/djgpp-linux64-gcc1210.tar.bz2 -o ~/djgpp-linux64-gcc1210.tar.bz2

      - name: Extract DJGPP toolchain
        run: |
          tar -xjf ~/djgpp-linux64-gcc1210.tar.bz2 -C ~/
      
      - name: Install libfl-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libfl-dev

      - name: Compile DJGPP library
        run: ./xmake.sh lib

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"        

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: nightly-tag-${{ steps.date.outputs.date }}
          release_name: nightly-release-${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
